### ISSUE TITLE
add to offical redmine plugin directory

### ISSUE THREAD

**Issue by fnkr** [giddie/redmine_default_assign#18]
Benefit: automatic update check

[![](https://ge1.me/348f653cb3c5403395c0/raw)](https://ge1.me/348f653cb3c5403395c0)

http://www.redmine.org/plugins

**Comment by giddie** [comment]
Hmm; good idea, but to be honest I'm not using Redmine at the moment, as I switched jobs a few months back. I'm happy to continue as de-facto custodian (which was kind of an accident actually!), but it might be best for someone else with more time for testing etc... to take care of this one?

Feel free to register the plugin yourself if you like, using either my Github repo or a fork of your own. And I'll continue to be open to pull requests, too.

**Comment by fnkr** [comment]
Which Redmine version does the plugin support? 2.6 is working, what about former versions?

**Comment by giddie** [comment]
I'm really not sure, I'm afraid. I believe there was a point (round about the switch to Rails 3) where a change in Redmine broke the plugin. It's possible that the changes required to fix the plugin at that point broke backward-compatibility, but I'm afraid I can't look into that at the moment. You might get some indications by looking through the git history.

**Comment by fnkr** [comment]
But it still should be working with 2.3.x, right?

**Comment by fnkr** [comment]
https://www.redmine.org/plugins/redmine_default_assign

**Comment by giddie** [comment]
You might want to use: https://github.com/giddie/redmine_default_assign.git instead of the SSH address, as the HTTP protocol will permit cloning without a Github account.

**Comment by fnkr** [comment]
Done.

**Comment by giddie** [comment]
Great; thanks for your contribution :)
