### ISSUE TITLE
Internal Server Error when trying to edit project or create new

### ISSUE THREAD

**Issue by vdmkenny** [giddie/redmine_default_assign#31]
We are running Redmine 3.0.3.stable, and I just installed your plugin. I wanted to set the default user for a project, and when clicking settings, it just gives me internal server error. Also when creating a new project. Removing the plugin solved this.

Is this a known issue? Can I provide you with any details to help?

**Comment by giddie** [comment]
Can you detail the process that you went through to install the plugin? Are you able to upgrade to Redmine 3.1.0?

**Comment by vdmkenny** [comment]
The git repo was cloned, packaged with fpm, and installed with a puppet run. Httpd was then restarted, the plugin was present and configurable on the plugins page, though project settings pages give the above effect.

**Comment by giddie** [comment]
Have you run the plugin migration rake task, as described in the Redmine Wiki?

http://www.redmine.org/projects/redmine/wiki/Plugins

**Comment by vdmkenny** [comment]
Okay. I skipped this step because there was no entry on that page for redmine 3.x. It works now, thanks for the help.
